### ISSUE TITLE
fatal: clone of 'git@github.com:engineerOfLies/simple_json.git' into submodule

### ISSUE THREAD

**Issue by Rickodesea** [engineerOfLies/gf3d#177]
fatal: clone of 'git@github.com:engineerOfLies/simple_json.git' into submodule

git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

This error occurs when running : git submodule update --init --recursive

**Comment by engineerOfLies** [comment]
it should work as long as you have SSH keys setup for git
