### ISSUE TITLE
Add support for the the latest vulkansdk VK_KHR_PORTABILITY_subset extension for macos

### ISSUE THREAD

**Issue by Vrajs16** [engineerOfLies/gf3d#42]
The information is written in the [docs](https://vulkan.lunarg.com/doc/view/latest/mac/getting_started.html#user-content-encountered-vk_error_incompatible_driver).

However the code snippet is written in c++ and would have to be implemented in c in this project. I tried doing so but go really confused as I never worked with the vulkan api before. However it should be pretty simple because if the VK_KHR_PORTABILITY_SUBSET_EXTENSION_NAME is set then add the flags and extensions.

**Comment by engineerOfLies** [comment]
can you provide where in the gf3d code base this needs to go?
I think I have an idea and why I omitted it.  It should be simple if it is what I think you mean

**Comment by Vrajs16** [comment]
After working with the codebase, I just have to add the extension to the config file and it worked. So this is no not necessary and this issue can be closed.
